apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcbsfl-nginx-inline
  labels:
    app: bcbsfl-nginx-inline
  annotations:
    # Optional: make Argo apply this AFTER the BuildConfig
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcbsfl-nginx-inline
  template:
    metadata:
      labels:
        app: bcbsfl-nginx-inline
    spec:
      imagePullSecrets:
        - name: n5bp-test-pull-secret
      containers:
        - name: nginx
          image: quay-enterprise.apps.ose4-dev.bcbsfl.com/n5bp/argocd-cicd:pavan3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080   # change if your base image listens on a different port
              name: http
