apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-build-demo.fullname" . }}
  labels:
    {{- include "helm-build-demo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "helm-build-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: ClusterIP
