apiVersion: v1
kind: Service
metadata:
  name: bcbsfl-nginx-inline
  labels:
    app: bcbsfl-nginx-inline
spec:
  selector:
    app: bcbsfl-nginx-inline
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
