# Image / registry settings
image:
  registry: quay.io
  org: bcbsfl             # <--- change if your Quay org is different
  name: chatbot-sample    # <--- change to your app name in Quay
  tag: "0.1.0"

  # Secret used to PUSH to Quay (BuildConfig) and PULL from Quay (Deployment)
  registrySecretName: quay-registry-secret

service:
  port: 8080

# Quay dockerconfigjson (base64 of ENTIRE ~/.docker/config.json)
# Run on your machine:
#   cat ~/.docker/config.json | base64 -w0
# Then paste the output below.
quay:
  dockerconfigjson: "PASTE_BASE64_DOCKERCONFIGJSON_HERE"
